### ISSUE TITLE
In commit 197381a39 I changed to refer to figures in this repo (not the quant-bio one, as they don't need to be repeated there).

### ISSUE THREAD

**Issue by andrew-edwards** [quantitative-biology/module-5-optimization#4]
See 197381a39.
I presume the figures are all the same. When I build they come out smaller than Kim's build on https://quantitative-biology.github.io/Advanced_Quant_Bio.github.io/optimization.html   , but it doesn't matter which figures I refer to, or if I change the size options. 

I do have the other modules commented out right now, so maybe something permanent gets changed in those. Or it's just a difference in our builds (which shouldn't really happen, but is kind of okay). 

There's unnecessary stuff in quant-bio/ repo, so I'm trying to create a simplified version (not posted yet).

Anyway, please just confirm the figures are the same - I think they are.

**Comment by kcudding** [comment]
not entirely sure what you are up to? figs need to be in the doc folder yes?

**Comment by andrew-edwards** [comment]
They are all in their respective module folders, so don't need to be copied over into the repo that builds the whole document. New simplified repo for building it all is https://github.com/quantitative-biology/build-all-modules   Just contains four bookdown files, referring to the five `module-XX-...` where all the code is.
