### ISSUE TITLE
Figure numbering is both hard-wired and automated

### ISSUE THREAD

**Issue by andrew-edwards** [quantitative-biology/module-5-optimization#5]
There are things like
```
fig.cap="Figure 2: Fermat's Theorem..."
```
but the numbering gets done automatically, so it comes out as "Figure 8.1: Figure 2: Fermat's Theorem..."

I was just going to fix it quickly but noticed that the references are to 'Figure 2' etc., so need proper automated cross-referencing.

(Would have looked fine before it was made into a part of the whole "book").

**Comment by kcudding** [comment]
fixed
